services:
  backend:
    build:
      context: ./backend

    container_name: foodiek-backend-compose

    ports:
      - "3000:3000"

    env_file:
      - ./backend/.env.docker

  frontend:
    build:
      context: ./frontend/vite-project

    container_name: foodiek-frontend-compose

    ports:
      - "5173:5173"

    depends_on:
      - backend
